### PR TITLE
Fix this.lexer undefined, fixes #246

### LINKED ISSUE #246: Exception thrown trying to use parser generated by 0.4.14
I'm using Jison 0.4.14 to try to generate a parser for [this grammar](https://github.com/markwatkinson/loljs/blob/18fee35f3f478cbd38bc50cdfec56db30e526e02/src/loljs.jison), which is created using [this script](https://github.com/markwatkinson/loljs/blob/18fee35f3f478cbd38bc50cdfec56db30e526e02/src/generate.js). The parser is generated, but warns of two conflicts (which I don't think should affect this, but I may be wrong).

Then trying to use it in a Node (v0.10.25) REPL, I'm getting:
```
> var p = require('./parser.js').parser
undefined
> p
{ yy: {} }
> p.parse("1")
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.parse (/home/mark/projects/loljs/parser.js:312:24)
    at repl:1:4
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

The line it's referencing (parser.js:312) is 
```javascript
var lexer = Object.create(this.lexer);
```

and `this.lexer` is undefined. I can't see any other reference to `this.lexer` anywhere in the file.

Here's the generated parser: https://gist.github.com/markwatkinson/c211a15e08d43c71e447

0.4.15 hits the same problem.
0.4.13 seems to work ok

### PR DESCRIPTION
**Pull request by nolanlawson**
It seems that 9e0cc65 introduced a bug in the generated
code, such that `this.lexer` is undefined, and so it
throws a runtime error.

This fixes the bug, and also adds a test to reproduce the
error. The test fails before the fix, but succeeds after.
I ran the tests and confirmed 100% success and no errors.

### CODE REVIEW

File: tests/parser/generator.js [hunk 1]
```diff
@@ -346,3 +349,33 @@ exports["test module include with each generator type"] = function () {
...
+      '%lex\n%%\n\n\\s+                   /* skip whitespace */\n' +
+      '("happy")             return \'happy\'\n' +
+      '("joy")               return \'joy\'\n' +
+      '<<EOF>>               return \'EOF\'\n\n' +
+      '/lex\n\n%start expressions\n\n' +
+      '%ebnf\n\n%%\n\n' +
+      'expressions\n    : e EOF\n        {return $1;}\n    ;\n\n' +
+      'e\n    : phrase+ \'joy\'? -> $1 + \' \' + yytext \n    ;\n\n' +
+      'phrase\n    : \'happy\' \'happy\' \'joy\' \'joy\' ' +
+      ' -> [$1, $2, $3, $4].join(\' \'); \n    ;';
```
Comment (nolanlawson) [inline tests/parser/generator.js]: Yes, I actually wrote this just for the test. Fun exercise. :)

**Comment by edge** [comment]
+1, can confirm that this fixes #246.

**Comment by edi9999** [comment]
Please merge :-), I'm encountering the same problem

**Comment by kether667** [comment]
+1 i confirm it fixes the issue too

**Comment by nolanlawson** [comment]
For anyone who's stuck waiting for a merge, you can add this to your `package.json`:

```
  "jison": "nolanlawson/jison#246"
```
